// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ledx2xn_ec_shm.proto

#ifndef PROTOBUF_ledx2xn_5fec_5fshm_2eproto__INCLUDED
#define PROTOBUF_ledx2xn_5fec_5fshm_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "component_base.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ledx2xn_5fec_5fshm_2eproto();
void protobuf_AssignDesc_ledx2xn_5fec_5fshm_2eproto();
void protobuf_ShutdownFile_ledx2xn_5fec_5fshm_2eproto();

class M3LedX2XNEcShmStatus;
class M3LedX2XNEcShmCommand;
class M3LedX2XNEcShmParam;

// ===================================================================

class M3LedX2XNEcShmStatus : public ::google::protobuf::Message {
 public:
  M3LedX2XNEcShmStatus();
  virtual ~M3LedX2XNEcShmStatus();

  M3LedX2XNEcShmStatus(const M3LedX2XNEcShmStatus& from);

  inline M3LedX2XNEcShmStatus& operator=(const M3LedX2XNEcShmStatus& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const M3LedX2XNEcShmStatus& default_instance();

  void Swap(M3LedX2XNEcShmStatus* other);

  // implements Message ----------------------------------------------

  M3LedX2XNEcShmStatus* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const M3LedX2XNEcShmStatus& from);
  void MergeFrom(const M3LedX2XNEcShmStatus& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .M3BaseStatus base = 1;
  inline bool has_base() const;
  inline void clear_base();
  static const int kBaseFieldNumber = 1;
  inline const ::M3BaseStatus& base() const;
  inline ::M3BaseStatus* mutable_base();
  inline ::M3BaseStatus* release_base();
  inline void set_allocated_base(::M3BaseStatus* base);

  // optional double test = 2;
  inline bool has_test() const;
  inline void clear_test();
  static const int kTestFieldNumber = 2;
  inline double test() const;
  inline void set_test(double value);

  // @@protoc_insertion_point(class_scope:M3LedX2XNEcShmStatus)
 private:
  inline void set_has_base();
  inline void clear_has_base();
  inline void set_has_test();
  inline void clear_has_test();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::M3BaseStatus* base_;
  double test_;
  friend void  protobuf_AddDesc_ledx2xn_5fec_5fshm_2eproto();
  friend void protobuf_AssignDesc_ledx2xn_5fec_5fshm_2eproto();
  friend void protobuf_ShutdownFile_ledx2xn_5fec_5fshm_2eproto();

  void InitAsDefaultInstance();
  static M3LedX2XNEcShmStatus* default_instance_;
};
// -------------------------------------------------------------------

class M3LedX2XNEcShmCommand : public ::google::protobuf::Message {
 public:
  M3LedX2XNEcShmCommand();
  virtual ~M3LedX2XNEcShmCommand();

  M3LedX2XNEcShmCommand(const M3LedX2XNEcShmCommand& from);

  inline M3LedX2XNEcShmCommand& operator=(const M3LedX2XNEcShmCommand& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const M3LedX2XNEcShmCommand& default_instance();

  void Swap(M3LedX2XNEcShmCommand* other);

  // implements Message ----------------------------------------------

  M3LedX2XNEcShmCommand* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const M3LedX2XNEcShmCommand& from);
  void MergeFrom(const M3LedX2XNEcShmCommand& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double test = 1;
  inline bool has_test() const;
  inline void clear_test();
  static const int kTestFieldNumber = 1;
  inline double test() const;
  inline void set_test(double value);

  // @@protoc_insertion_point(class_scope:M3LedX2XNEcShmCommand)
 private:
  inline void set_has_test();
  inline void clear_has_test();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double test_;
  friend void  protobuf_AddDesc_ledx2xn_5fec_5fshm_2eproto();
  friend void protobuf_AssignDesc_ledx2xn_5fec_5fshm_2eproto();
  friend void protobuf_ShutdownFile_ledx2xn_5fec_5fshm_2eproto();

  void InitAsDefaultInstance();
  static M3LedX2XNEcShmCommand* default_instance_;
};
// -------------------------------------------------------------------

class M3LedX2XNEcShmParam : public ::google::protobuf::Message {
 public:
  M3LedX2XNEcShmParam();
  virtual ~M3LedX2XNEcShmParam();

  M3LedX2XNEcShmParam(const M3LedX2XNEcShmParam& from);

  inline M3LedX2XNEcShmParam& operator=(const M3LedX2XNEcShmParam& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const M3LedX2XNEcShmParam& default_instance();

  void Swap(M3LedX2XNEcShmParam* other);

  // implements Message ----------------------------------------------

  M3LedX2XNEcShmParam* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const M3LedX2XNEcShmParam& from);
  void MergeFrom(const M3LedX2XNEcShmParam& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double test = 1;
  inline bool has_test() const;
  inline void clear_test();
  static const int kTestFieldNumber = 1;
  inline double test() const;
  inline void set_test(double value);

  // @@protoc_insertion_point(class_scope:M3LedX2XNEcShmParam)
 private:
  inline void set_has_test();
  inline void clear_has_test();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double test_;
  friend void  protobuf_AddDesc_ledx2xn_5fec_5fshm_2eproto();
  friend void protobuf_AssignDesc_ledx2xn_5fec_5fshm_2eproto();
  friend void protobuf_ShutdownFile_ledx2xn_5fec_5fshm_2eproto();

  void InitAsDefaultInstance();
  static M3LedX2XNEcShmParam* default_instance_;
};
// ===================================================================


// ===================================================================

// M3LedX2XNEcShmStatus

// optional .M3BaseStatus base = 1;
inline bool M3LedX2XNEcShmStatus::has_base() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void M3LedX2XNEcShmStatus::set_has_base() {
  _has_bits_[0] |= 0x00000001u;
}
inline void M3LedX2XNEcShmStatus::clear_has_base() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void M3LedX2XNEcShmStatus::clear_base() {
  if (base_ != NULL) base_->::M3BaseStatus::Clear();
  clear_has_base();
}
inline const ::M3BaseStatus& M3LedX2XNEcShmStatus::base() const {
  // @@protoc_insertion_point(field_get:M3LedX2XNEcShmStatus.base)
  return base_ != NULL ? *base_ : *default_instance_->base_;
}
inline ::M3BaseStatus* M3LedX2XNEcShmStatus::mutable_base() {
  set_has_base();
  if (base_ == NULL) base_ = new ::M3BaseStatus;
  // @@protoc_insertion_point(field_mutable:M3LedX2XNEcShmStatus.base)
  return base_;
}
inline ::M3BaseStatus* M3LedX2XNEcShmStatus::release_base() {
  clear_has_base();
  ::M3BaseStatus* temp = base_;
  base_ = NULL;
  return temp;
}
inline void M3LedX2XNEcShmStatus::set_allocated_base(::M3BaseStatus* base) {
  delete base_;
  base_ = base;
  if (base) {
    set_has_base();
  } else {
    clear_has_base();
  }
  // @@protoc_insertion_point(field_set_allocated:M3LedX2XNEcShmStatus.base)
}

// optional double test = 2;
inline bool M3LedX2XNEcShmStatus::has_test() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void M3LedX2XNEcShmStatus::set_has_test() {
  _has_bits_[0] |= 0x00000002u;
}
inline void M3LedX2XNEcShmStatus::clear_has_test() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void M3LedX2XNEcShmStatus::clear_test() {
  test_ = 0;
  clear_has_test();
}
inline double M3LedX2XNEcShmStatus::test() const {
  // @@protoc_insertion_point(field_get:M3LedX2XNEcShmStatus.test)
  return test_;
}
inline void M3LedX2XNEcShmStatus::set_test(double value) {
  set_has_test();
  test_ = value;
  // @@protoc_insertion_point(field_set:M3LedX2XNEcShmStatus.test)
}

// -------------------------------------------------------------------

// M3LedX2XNEcShmCommand

// optional double test = 1;
inline bool M3LedX2XNEcShmCommand::has_test() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void M3LedX2XNEcShmCommand::set_has_test() {
  _has_bits_[0] |= 0x00000001u;
}
inline void M3LedX2XNEcShmCommand::clear_has_test() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void M3LedX2XNEcShmCommand::clear_test() {
  test_ = 0;
  clear_has_test();
}
inline double M3LedX2XNEcShmCommand::test() const {
  // @@protoc_insertion_point(field_get:M3LedX2XNEcShmCommand.test)
  return test_;
}
inline void M3LedX2XNEcShmCommand::set_test(double value) {
  set_has_test();
  test_ = value;
  // @@protoc_insertion_point(field_set:M3LedX2XNEcShmCommand.test)
}

// -------------------------------------------------------------------

// M3LedX2XNEcShmParam

// optional double test = 1;
inline bool M3LedX2XNEcShmParam::has_test() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void M3LedX2XNEcShmParam::set_has_test() {
  _has_bits_[0] |= 0x00000001u;
}
inline void M3LedX2XNEcShmParam::clear_has_test() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void M3LedX2XNEcShmParam::clear_test() {
  test_ = 0;
  clear_has_test();
}
inline double M3LedX2XNEcShmParam::test() const {
  // @@protoc_insertion_point(field_get:M3LedX2XNEcShmParam.test)
  return test_;
}
inline void M3LedX2XNEcShmParam::set_test(double value) {
  set_has_test();
  test_ = value;
  // @@protoc_insertion_point(field_set:M3LedX2XNEcShmParam.test)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ledx2xn_5fec_5fshm_2eproto__INCLUDED
