// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loadx6.proto

#ifndef PROTOBUF_loadx6_2eproto__INCLUDED
#define PROTOBUF_loadx6_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "component_base.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_loadx6_2eproto();
void protobuf_AssignDesc_loadx6_2eproto();
void protobuf_ShutdownFile_loadx6_2eproto();

class M3LoadX6Status;
class M3LoadX6Command;
class M3LoadX6Param;

// ===================================================================

class M3LoadX6Status : public ::google::protobuf::Message {
 public:
  M3LoadX6Status();
  virtual ~M3LoadX6Status();

  M3LoadX6Status(const M3LoadX6Status& from);

  inline M3LoadX6Status& operator=(const M3LoadX6Status& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const M3LoadX6Status& default_instance();

  void Swap(M3LoadX6Status* other);

  // implements Message ----------------------------------------------

  M3LoadX6Status* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const M3LoadX6Status& from);
  void MergeFrom(const M3LoadX6Status& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .M3BaseStatus base = 1;
  inline bool has_base() const;
  inline void clear_base();
  static const int kBaseFieldNumber = 1;
  inline const ::M3BaseStatus& base() const;
  inline ::M3BaseStatus* mutable_base();
  inline ::M3BaseStatus* release_base();
  inline void set_allocated_base(::M3BaseStatus* base);

  // repeated double wrench = 2;
  inline int wrench_size() const;
  inline void clear_wrench();
  static const int kWrenchFieldNumber = 2;
  inline double wrench(int index) const;
  inline void set_wrench(int index, double value);
  inline void add_wrench(double value);
  inline const ::google::protobuf::RepeatedField< double >&
      wrench() const;
  inline ::google::protobuf::RepeatedField< double >*
      mutable_wrench();

  // optional double adc_ext_0 = 3;
  inline bool has_adc_ext_0() const;
  inline void clear_adc_ext_0();
  static const int kAdcExt0FieldNumber = 3;
  inline double adc_ext_0() const;
  inline void set_adc_ext_0(double value);

  // optional double adc_ext_1 = 4;
  inline bool has_adc_ext_1() const;
  inline void clear_adc_ext_1();
  static const int kAdcExt1FieldNumber = 4;
  inline double adc_ext_1() const;
  inline void set_adc_ext_1(double value);

  // optional double adc_ext_2 = 5;
  inline bool has_adc_ext_2() const;
  inline void clear_adc_ext_2();
  static const int kAdcExt2FieldNumber = 5;
  inline double adc_ext_2() const;
  inline void set_adc_ext_2(double value);

  // optional double dig_ext_0 = 6;
  inline bool has_dig_ext_0() const;
  inline void clear_dig_ext_0();
  static const int kDigExt0FieldNumber = 6;
  inline double dig_ext_0() const;
  inline void set_dig_ext_0(double value);

  // @@protoc_insertion_point(class_scope:M3LoadX6Status)
 private:
  inline void set_has_base();
  inline void clear_has_base();
  inline void set_has_adc_ext_0();
  inline void clear_has_adc_ext_0();
  inline void set_has_adc_ext_1();
  inline void clear_has_adc_ext_1();
  inline void set_has_adc_ext_2();
  inline void clear_has_adc_ext_2();
  inline void set_has_dig_ext_0();
  inline void clear_has_dig_ext_0();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::M3BaseStatus* base_;
  ::google::protobuf::RepeatedField< double > wrench_;
  double adc_ext_0_;
  double adc_ext_1_;
  double adc_ext_2_;
  double dig_ext_0_;
  friend void  protobuf_AddDesc_loadx6_2eproto();
  friend void protobuf_AssignDesc_loadx6_2eproto();
  friend void protobuf_ShutdownFile_loadx6_2eproto();

  void InitAsDefaultInstance();
  static M3LoadX6Status* default_instance_;
};
// -------------------------------------------------------------------

class M3LoadX6Command : public ::google::protobuf::Message {
 public:
  M3LoadX6Command();
  virtual ~M3LoadX6Command();

  M3LoadX6Command(const M3LoadX6Command& from);

  inline M3LoadX6Command& operator=(const M3LoadX6Command& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const M3LoadX6Command& default_instance();

  void Swap(M3LoadX6Command* other);

  // implements Message ----------------------------------------------

  M3LoadX6Command* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const M3LoadX6Command& from);
  void MergeFrom(const M3LoadX6Command& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:M3LoadX6Command)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_loadx6_2eproto();
  friend void protobuf_AssignDesc_loadx6_2eproto();
  friend void protobuf_ShutdownFile_loadx6_2eproto();

  void InitAsDefaultInstance();
  static M3LoadX6Command* default_instance_;
};
// -------------------------------------------------------------------

class M3LoadX6Param : public ::google::protobuf::Message {
 public:
  M3LoadX6Param();
  virtual ~M3LoadX6Param();

  M3LoadX6Param(const M3LoadX6Param& from);

  inline M3LoadX6Param& operator=(const M3LoadX6Param& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const M3LoadX6Param& default_instance();

  void Swap(M3LoadX6Param* other);

  // implements Message ----------------------------------------------

  M3LoadX6Param* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const M3LoadX6Param& from);
  void MergeFrom(const M3LoadX6Param& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:M3LoadX6Param)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_loadx6_2eproto();
  friend void protobuf_AssignDesc_loadx6_2eproto();
  friend void protobuf_ShutdownFile_loadx6_2eproto();

  void InitAsDefaultInstance();
  static M3LoadX6Param* default_instance_;
};
// ===================================================================


// ===================================================================

// M3LoadX6Status

// optional .M3BaseStatus base = 1;
inline bool M3LoadX6Status::has_base() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void M3LoadX6Status::set_has_base() {
  _has_bits_[0] |= 0x00000001u;
}
inline void M3LoadX6Status::clear_has_base() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void M3LoadX6Status::clear_base() {
  if (base_ != NULL) base_->::M3BaseStatus::Clear();
  clear_has_base();
}
inline const ::M3BaseStatus& M3LoadX6Status::base() const {
  // @@protoc_insertion_point(field_get:M3LoadX6Status.base)
  return base_ != NULL ? *base_ : *default_instance_->base_;
}
inline ::M3BaseStatus* M3LoadX6Status::mutable_base() {
  set_has_base();
  if (base_ == NULL) base_ = new ::M3BaseStatus;
  // @@protoc_insertion_point(field_mutable:M3LoadX6Status.base)
  return base_;
}
inline ::M3BaseStatus* M3LoadX6Status::release_base() {
  clear_has_base();
  ::M3BaseStatus* temp = base_;
  base_ = NULL;
  return temp;
}
inline void M3LoadX6Status::set_allocated_base(::M3BaseStatus* base) {
  delete base_;
  base_ = base;
  if (base) {
    set_has_base();
  } else {
    clear_has_base();
  }
  // @@protoc_insertion_point(field_set_allocated:M3LoadX6Status.base)
}

// repeated double wrench = 2;
inline int M3LoadX6Status::wrench_size() const {
  return wrench_.size();
}
inline void M3LoadX6Status::clear_wrench() {
  wrench_.Clear();
}
inline double M3LoadX6Status::wrench(int index) const {
  // @@protoc_insertion_point(field_get:M3LoadX6Status.wrench)
  return wrench_.Get(index);
}
inline void M3LoadX6Status::set_wrench(int index, double value) {
  wrench_.Set(index, value);
  // @@protoc_insertion_point(field_set:M3LoadX6Status.wrench)
}
inline void M3LoadX6Status::add_wrench(double value) {
  wrench_.Add(value);
  // @@protoc_insertion_point(field_add:M3LoadX6Status.wrench)
}
inline const ::google::protobuf::RepeatedField< double >&
M3LoadX6Status::wrench() const {
  // @@protoc_insertion_point(field_list:M3LoadX6Status.wrench)
  return wrench_;
}
inline ::google::protobuf::RepeatedField< double >*
M3LoadX6Status::mutable_wrench() {
  // @@protoc_insertion_point(field_mutable_list:M3LoadX6Status.wrench)
  return &wrench_;
}

// optional double adc_ext_0 = 3;
inline bool M3LoadX6Status::has_adc_ext_0() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void M3LoadX6Status::set_has_adc_ext_0() {
  _has_bits_[0] |= 0x00000004u;
}
inline void M3LoadX6Status::clear_has_adc_ext_0() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void M3LoadX6Status::clear_adc_ext_0() {
  adc_ext_0_ = 0;
  clear_has_adc_ext_0();
}
inline double M3LoadX6Status::adc_ext_0() const {
  // @@protoc_insertion_point(field_get:M3LoadX6Status.adc_ext_0)
  return adc_ext_0_;
}
inline void M3LoadX6Status::set_adc_ext_0(double value) {
  set_has_adc_ext_0();
  adc_ext_0_ = value;
  // @@protoc_insertion_point(field_set:M3LoadX6Status.adc_ext_0)
}

// optional double adc_ext_1 = 4;
inline bool M3LoadX6Status::has_adc_ext_1() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void M3LoadX6Status::set_has_adc_ext_1() {
  _has_bits_[0] |= 0x00000008u;
}
inline void M3LoadX6Status::clear_has_adc_ext_1() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void M3LoadX6Status::clear_adc_ext_1() {
  adc_ext_1_ = 0;
  clear_has_adc_ext_1();
}
inline double M3LoadX6Status::adc_ext_1() const {
  // @@protoc_insertion_point(field_get:M3LoadX6Status.adc_ext_1)
  return adc_ext_1_;
}
inline void M3LoadX6Status::set_adc_ext_1(double value) {
  set_has_adc_ext_1();
  adc_ext_1_ = value;
  // @@protoc_insertion_point(field_set:M3LoadX6Status.adc_ext_1)
}

// optional double adc_ext_2 = 5;
inline bool M3LoadX6Status::has_adc_ext_2() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void M3LoadX6Status::set_has_adc_ext_2() {
  _has_bits_[0] |= 0x00000010u;
}
inline void M3LoadX6Status::clear_has_adc_ext_2() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void M3LoadX6Status::clear_adc_ext_2() {
  adc_ext_2_ = 0;
  clear_has_adc_ext_2();
}
inline double M3LoadX6Status::adc_ext_2() const {
  // @@protoc_insertion_point(field_get:M3LoadX6Status.adc_ext_2)
  return adc_ext_2_;
}
inline void M3LoadX6Status::set_adc_ext_2(double value) {
  set_has_adc_ext_2();
  adc_ext_2_ = value;
  // @@protoc_insertion_point(field_set:M3LoadX6Status.adc_ext_2)
}

// optional double dig_ext_0 = 6;
inline bool M3LoadX6Status::has_dig_ext_0() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void M3LoadX6Status::set_has_dig_ext_0() {
  _has_bits_[0] |= 0x00000020u;
}
inline void M3LoadX6Status::clear_has_dig_ext_0() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void M3LoadX6Status::clear_dig_ext_0() {
  dig_ext_0_ = 0;
  clear_has_dig_ext_0();
}
inline double M3LoadX6Status::dig_ext_0() const {
  // @@protoc_insertion_point(field_get:M3LoadX6Status.dig_ext_0)
  return dig_ext_0_;
}
inline void M3LoadX6Status::set_dig_ext_0(double value) {
  set_has_dig_ext_0();
  dig_ext_0_ = value;
  // @@protoc_insertion_point(field_set:M3LoadX6Status.dig_ext_0)
}

// -------------------------------------------------------------------

// M3LoadX6Command

// -------------------------------------------------------------------

// M3LoadX6Param


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_loadx6_2eproto__INCLUDED
