controller_list:
  - name: fake_right_arm_controller
    joints:
      - right_arm_j0
      - right_arm_j1
      - right_arm_j2
      - right_arm_j3
      - right_arm_j4
      - right_arm_j5
      - right_arm_j6
  - name: fake_head_controller
    joints:
      - head_j0
      - head_j1
      - head_j2
      - head_j3
      - head_j4
      - head_j5
      - head_j7_rt_eyelid_bottom
      - head_j7_rt_eyelid_top
      - head_j6
      - head_j7_lt_eyelid_bottom
      - head_j7_lt_eyelid_top
  - name: fake_left_arm_controller
    joints:
      - left_arm_j0
      - left_arm_j1
      - left_arm_j2
      - left_arm_j3
      - left_arm_j4
      - left_arm_j5
      - left_arm_j6
  - name: fake_both_arms_controller
    joints:
      - left_arm_j0
      - left_arm_j1
      - left_arm_j2
      - left_arm_j3
      - left_arm_j4
      - left_arm_j5
      - left_arm_j6
      - right_arm_j0
      - right_arm_j1
      - right_arm_j2
      - right_arm_j3
      - right_arm_j4
      - right_arm_j5
      - right_arm_j6
  - name: fake_left_hand_controller
    joints:
      - left_hand_j0
      - left_hand_j1
      - left_hand_j2
      - left_hand_j3
      - left_hand_j12
      - left_hand_j13
      - left_hand_j14
      - left_hand_j15
      - left_hand_j4
      - left_hand_j5
      - left_hand_j6
      - left_hand_j7
      - left_hand_j8
      - left_hand_j9
      - left_hand_j10
      - left_hand_j11
  - name: fake_right_hand_controller
    joints:
      - right_hand_j0
      - right_hand_j1
      - right_hand_j2
      - right_hand_j3
      - right_hand_j12
      - right_hand_j13
      - right_hand_j14
      - right_hand_j15
      - right_hand_j4
      - right_hand_j5
      - right_hand_j6
      - right_hand_j7
      - right_hand_j8
      - right_hand_j9
      - right_hand_j10
      - right_hand_j11