joint_limits:
  left_hand_j0:
    has_velocity_limits: true
    max_velocity: 0.349065850399
    has_acceleration_limits: false
    max_acceleration: 0
  right_hand_j0:
    has_velocity_limits: true
    max_velocity: 0.349065850399
    has_acceleration_limits: false
    max_acceleration: 0
  head_j7_lt_eyelid_top:
    has_velocity_limits: true
    max_velocity: 27.9252680319
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_j2:
    has_velocity_limits: true
    max_velocity: 0.872664625997
    has_acceleration_limits: false
    max_acceleration: 0
  right_hand_j7:
    has_velocity_limits: true
    max_velocity: 27.9252680319
    has_acceleration_limits: false
    max_acceleration: 0
  right_hand_j2:
    has_velocity_limits: true
    max_velocity: 0.872664625997
    has_acceleration_limits: false
    max_acceleration: 0
  head_j6:
    has_velocity_limits: true
    max_velocity: 27.9252680319
    has_acceleration_limits: false
    max_acceleration: 0
  left_hand_j6:
    has_velocity_limits: true
    max_velocity: 27.9252680319
    has_acceleration_limits: false
    max_acceleration: 0
  right_hand_j13:
    has_velocity_limits: true
    max_velocity: 27.9252680319
    has_acceleration_limits: false
    max_acceleration: 0
  right_hand_j15:
    has_velocity_limits: true
    max_velocity: 27.9252680319
    has_acceleration_limits: false
    max_acceleration: 0
  right_hand_j4:
    has_velocity_limits: true
    max_velocity: 0.872664625997
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_j6:
    has_velocity_limits: true
    max_velocity: 0.698131700798
    has_acceleration_limits: false
    max_acceleration: 0
  right_hand_j12:
    has_velocity_limits: true
    max_velocity: 0.872664625997
    has_acceleration_limits: false
    max_acceleration: 0
  head_j3:
    has_velocity_limits: true
    max_velocity: 0.872664625997
    has_acceleration_limits: false
    max_acceleration: 0
  right_hand_j3:
    has_velocity_limits: true
    max_velocity: 0.872664625997
    has_acceleration_limits: false
    max_acceleration: 0
  left_hand_j2:
    has_velocity_limits: true
    max_velocity: 0.872664625997
    has_acceleration_limits: false
    max_acceleration: 0
  left_hand_j11:
    has_velocity_limits: true
    max_velocity: 27.9252680319
    has_acceleration_limits: false
    max_acceleration: 0
  left_hand_j7:
    has_velocity_limits: true
    max_velocity: 27.9252680319
    has_acceleration_limits: false
    max_acceleration: 0
  head_j5:
    has_velocity_limits: true
    max_velocity: 27.9252680319
    has_acceleration_limits: false
    max_acceleration: 0
  head_j7_rt_eyelid_bottom:
    has_velocity_limits: true
    max_velocity: 27.9252680319
    has_acceleration_limits: false
    max_acceleration: 0
  head_j4:
    has_velocity_limits: true
    max_velocity: 27.9252680319
    has_acceleration_limits: false
    max_acceleration: 0
  right_hand_j8:
    has_velocity_limits: true
    max_velocity: 0.872664625997
    has_acceleration_limits: false
    max_acceleration: 0
  right_hand_j10:
    has_velocity_limits: true
    max_velocity: 27.9252680319
    has_acceleration_limits: false
    max_acceleration: 0
  left_hand_j8:
    has_velocity_limits: true
    max_velocity: 0.872664625997
    has_acceleration_limits: false
    max_acceleration: 0
  left_hand_j9:
    has_velocity_limits: true
    max_velocity: 27.9252680319
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_j5:
    has_velocity_limits: true
    max_velocity: 0.698131700798
    has_acceleration_limits: false
    max_acceleration: 0
  left_hand_j1:
    has_velocity_limits: true
    max_velocity: 1.308996939
    has_acceleration_limits: false
    max_acceleration: 0
  left_arm_j5:
    has_velocity_limits: true
    max_velocity: 0.698131700798
    has_acceleration_limits: false
    max_acceleration: 0
  left_hand_j12:
    has_velocity_limits: true
    max_velocity: 0.872664625997
    has_acceleration_limits: false
    max_acceleration: 0
  left_arm_j2:
    has_velocity_limits: true
    max_velocity: 0.872664625997
    has_acceleration_limits: false
    max_acceleration: 0
  left_hand_j14:
    has_velocity_limits: true
    max_velocity: 27.9252680319
    has_acceleration_limits: false
    max_acceleration: 0
  left_arm_j0:
    has_velocity_limits: true
    max_velocity: 0.523598775598
    has_acceleration_limits: false
    max_acceleration: 0
  left_arm_j1:
    has_velocity_limits: true
    max_velocity: 0.523598775598
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_j4:
    has_velocity_limits: true
    max_velocity: 2.61799387799
    has_acceleration_limits: false
    max_acceleration: 0
  head_j0:
    has_velocity_limits: true
    max_velocity: 0.349065850399
    has_acceleration_limits: false
    max_acceleration: 0
  right_hand_j14:
    has_velocity_limits: true
    max_velocity: 27.9252680319
    has_acceleration_limits: false
    max_acceleration: 0
  right_hand_j9:
    has_velocity_limits: true
    max_velocity: 27.9252680319
    has_acceleration_limits: false
    max_acceleration: 0
  head_j1:
    has_velocity_limits: true
    max_velocity: 1.308996939
    has_acceleration_limits: false
    max_acceleration: 0
  left_hand_j13:
    has_velocity_limits: true
    max_velocity: 27.9252680319
    has_acceleration_limits: false
    max_acceleration: 0
  left_hand_j5:
    has_velocity_limits: true
    max_velocity: 27.9252680319
    has_acceleration_limits: false
    max_acceleration: 0
  left_arm_j4:
    has_velocity_limits: true
    max_velocity: 2.61799387799
    has_acceleration_limits: false
    max_acceleration: 0
  left_hand_j15:
    has_velocity_limits: true
    max_velocity: 27.9252680319
    has_acceleration_limits: false
    max_acceleration: 0
  right_hand_j11:
    has_velocity_limits: true
    max_velocity: 27.9252680319
    has_acceleration_limits: false
    max_acceleration: 0
  head_j7_lt_eyelid_bottom:
    has_velocity_limits: true
    max_velocity: 27.9252680319
    has_acceleration_limits: false
    max_acceleration: 0
  left_arm_j3:
    has_velocity_limits: true
    max_velocity: 0.872664625997
    has_acceleration_limits: false
    max_acceleration: 0
  left_hand_j3:
    has_velocity_limits: true
    max_velocity: 0.872664625997
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_j1:
    has_velocity_limits: true
    max_velocity: 0.523598775598
    has_acceleration_limits: false
    max_acceleration: 0
  left_arm_j6:
    has_velocity_limits: true
    max_velocity: 0.698131700798
    has_acceleration_limits: false
    max_acceleration: 0
  right_hand_j5:
    has_velocity_limits: true
    max_velocity: 27.9252680319
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_j0:
    has_velocity_limits: true
    max_velocity: 0.523598775598
    has_acceleration_limits: false
    max_acceleration: 0
  right_hand_j6:
    has_velocity_limits: true
    max_velocity: 27.9252680319
    has_acceleration_limits: false
    max_acceleration: 0
  head_j2:
    has_velocity_limits: true
    max_velocity: 0.872664625997
    has_acceleration_limits: false
    max_acceleration: 0
  head_j7_rt_eyelid_top:
    has_velocity_limits: true
    max_velocity: 27.9252680319
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_j3:
    has_velocity_limits: true
    max_velocity: 0.872664625997
    has_acceleration_limits: false
    max_acceleration: 0
  left_hand_j4:
    has_velocity_limits: true
    max_velocity: 0.872664625997
    has_acceleration_limits: false
    max_acceleration: 0
  right_hand_j1:
    has_velocity_limits: true
    max_velocity: 1.308996939
    has_acceleration_limits: false
    max_acceleration: 0
  left_hand_j10:
    has_velocity_limits: true
    max_velocity: 27.9252680319
    has_acceleration_limits: false
    max_acceleration: 0