/* Auto-generated by genmsg_cpp for file /home/meka/mekabot/m3meka/ros/shm_pwr_state_omnibase/msg/PowerState.msg */
#ifndef SHM_PWR_STATE_OMNIBASE_MESSAGE_POWERSTATE_H
#define SHM_PWR_STATE_OMNIBASE_MESSAGE_POWERSTATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace shm_pwr_state_omnibase
{
template <class ContainerAllocator>
struct PowerState_ {
  typedef PowerState_<ContainerAllocator> Type;

  PowerState_()
  : header()
  , bus_voltage(0.0)
  {
  }

  PowerState_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , bus_voltage(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _bus_voltage_type;
  float bus_voltage;


  typedef boost::shared_ptr< ::shm_pwr_state_omnibase::PowerState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::shm_pwr_state_omnibase::PowerState_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PowerState
typedef  ::shm_pwr_state_omnibase::PowerState_<std::allocator<void> > PowerState;

typedef boost::shared_ptr< ::shm_pwr_state_omnibase::PowerState> PowerStatePtr;
typedef boost::shared_ptr< ::shm_pwr_state_omnibase::PowerState const> PowerStateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::shm_pwr_state_omnibase::PowerState_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::shm_pwr_state_omnibase::PowerState_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace shm_pwr_state_omnibase

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::shm_pwr_state_omnibase::PowerState_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::shm_pwr_state_omnibase::PowerState_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::shm_pwr_state_omnibase::PowerState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "742d8d95fc3f65dac97a3a02ac8ccba9";
  }

  static const char* value(const  ::shm_pwr_state_omnibase::PowerState_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x742d8d95fc3f65daULL;
  static const uint64_t static_value2 = 0xc97a3a02ac8ccba9ULL;
};

template<class ContainerAllocator>
struct DataType< ::shm_pwr_state_omnibase::PowerState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "shm_pwr_state_omnibase/PowerState";
  }

  static const char* value(const  ::shm_pwr_state_omnibase::PowerState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::shm_pwr_state_omnibase::PowerState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float32 bus_voltage\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::shm_pwr_state_omnibase::PowerState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::shm_pwr_state_omnibase::PowerState_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::shm_pwr_state_omnibase::PowerState_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::shm_pwr_state_omnibase::PowerState_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.bus_voltage);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PowerState_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::shm_pwr_state_omnibase::PowerState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::shm_pwr_state_omnibase::PowerState_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "bus_voltage: ";
    Printer<float>::stream(s, indent + "  ", v.bus_voltage);
  }
};


} // namespace message_operations
} // namespace ros

#endif // SHM_PWR_STATE_OMNIBASE_MESSAGE_POWERSTATE_H

