// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: joint_array_mode.proto

#ifndef PROTOBUF_joint_5farray_5fmode_2eproto__INCLUDED
#define PROTOBUF_joint_5farray_5fmode_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_joint_5farray_5fmode_2eproto();
void protobuf_AssignDesc_joint_5farray_5fmode_2eproto();
void protobuf_ShutdownFile_joint_5farray_5fmode_2eproto();


enum JOINT_ARRAY_MODE {
  JOINT_ARRAY_MODE_OFF = 0,
  JOINT_ARRAY_MODE_PWM = 1,
  JOINT_ARRAY_MODE_TORQUE = 2,
  JOINT_ARRAY_MODE_THETA = 3,
  JOINT_ARRAY_MODE_TORQUE_GC = 4,
  JOINT_ARRAY_MODE_THETA_GC = 5,
  JOINT_ARRAY_MODE_THETA_MJ = 6,
  JOINT_ARRAY_MODE_THETA_GC_MJ = 7,
  JOINT_ARRAY_MODE_SPLINED_TRAJ = 8,
  JOINT_ARRAY_MODE_SPLINED_TRAJ_GC = 9,
  JOINT_ARRAY_MODE_TORQUE_SHM = 10,
  JOINT_ARRAY_MODE_ANGLE_SHM = 11,
  JOINT_ARRAY_MODE_POSE = 12,
  JOINT_ARRAY_MODE_TORQUE_GRAV_MODEL = 13,
  JOINT_ARRAY_MODE_IK = 14,
  JOINT_ARRAY_MODE_THETADOT_GC = 15,
  JOINT_ARRAY_MODE_THETADOT = 16
};
bool JOINT_ARRAY_MODE_IsValid(int value);
const JOINT_ARRAY_MODE JOINT_ARRAY_MODE_MIN = JOINT_ARRAY_MODE_OFF;
const JOINT_ARRAY_MODE JOINT_ARRAY_MODE_MAX = JOINT_ARRAY_MODE_THETADOT;
const int JOINT_ARRAY_MODE_ARRAYSIZE = JOINT_ARRAY_MODE_MAX + 1;

const ::google::protobuf::EnumDescriptor* JOINT_ARRAY_MODE_descriptor();
inline const ::std::string& JOINT_ARRAY_MODE_Name(JOINT_ARRAY_MODE value) {
  return ::google::protobuf::internal::NameOfEnum(
    JOINT_ARRAY_MODE_descriptor(), value);
}
inline bool JOINT_ARRAY_MODE_Parse(
    const ::std::string& name, JOINT_ARRAY_MODE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<JOINT_ARRAY_MODE>(
    JOINT_ARRAY_MODE_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::JOINT_ARRAY_MODE> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::JOINT_ARRAY_MODE>() {
  return ::JOINT_ARRAY_MODE_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_joint_5farray_5fmode_2eproto__INCLUDED
