// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log.proto

#ifndef PROTOBUF_log_2eproto__INCLUDED
#define PROTOBUF_log_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "component_base.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_log_2eproto();
void protobuf_AssignDesc_log_2eproto();
void protobuf_ShutdownFile_log_2eproto();

class M3MekaLogStatus;
class M3MekaLogParam;
class M3MekaLogCommand;

// ===================================================================

class M3MekaLogStatus : public ::google::protobuf::Message {
 public:
  M3MekaLogStatus();
  virtual ~M3MekaLogStatus();

  M3MekaLogStatus(const M3MekaLogStatus& from);

  inline M3MekaLogStatus& operator=(const M3MekaLogStatus& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const M3MekaLogStatus& default_instance();

  void Swap(M3MekaLogStatus* other);

  // implements Message ----------------------------------------------

  M3MekaLogStatus* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const M3MekaLogStatus& from);
  void MergeFrom(const M3MekaLogStatus& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .M3BaseStatus base = 1;
  inline bool has_base() const;
  inline void clear_base();
  static const int kBaseFieldNumber = 1;
  inline const ::M3BaseStatus& base() const;
  inline ::M3BaseStatus* mutable_base();
  inline ::M3BaseStatus* release_base();
  inline void set_allocated_base(::M3BaseStatus* base);

  // optional string path = 2;
  inline bool has_path() const;
  inline void clear_path();
  static const int kPathFieldNumber = 2;
  inline const ::std::string& path() const;
  inline void set_path(const ::std::string& value);
  inline void set_path(const char* value);
  inline void set_path(const char* value, size_t size);
  inline ::std::string* mutable_path();
  inline ::std::string* release_path();
  inline void set_allocated_path(::std::string* path);

  // optional string log_name = 3;
  inline bool has_log_name() const;
  inline void clear_log_name();
  static const int kLogNameFieldNumber = 3;
  inline const ::std::string& log_name() const;
  inline void set_log_name(const ::std::string& value);
  inline void set_log_name(const char* value);
  inline void set_log_name(const char* value, size_t size);
  inline ::std::string* mutable_log_name();
  inline ::std::string* release_log_name();
  inline void set_allocated_log_name(::std::string* log_name);

  // @@protoc_insertion_point(class_scope:M3MekaLogStatus)
 private:
  inline void set_has_base();
  inline void clear_has_base();
  inline void set_has_path();
  inline void clear_has_path();
  inline void set_has_log_name();
  inline void clear_has_log_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::M3BaseStatus* base_;
  ::std::string* path_;
  ::std::string* log_name_;
  friend void  protobuf_AddDesc_log_2eproto();
  friend void protobuf_AssignDesc_log_2eproto();
  friend void protobuf_ShutdownFile_log_2eproto();

  void InitAsDefaultInstance();
  static M3MekaLogStatus* default_instance_;
};
// -------------------------------------------------------------------

class M3MekaLogParam : public ::google::protobuf::Message {
 public:
  M3MekaLogParam();
  virtual ~M3MekaLogParam();

  M3MekaLogParam(const M3MekaLogParam& from);

  inline M3MekaLogParam& operator=(const M3MekaLogParam& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const M3MekaLogParam& default_instance();

  void Swap(M3MekaLogParam* other);

  // implements Message ----------------------------------------------

  M3MekaLogParam* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const M3MekaLogParam& from);
  void MergeFrom(const M3MekaLogParam& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double debug = 1;
  inline bool has_debug() const;
  inline void clear_debug();
  static const int kDebugFieldNumber = 1;
  inline double debug() const;
  inline void set_debug(double value);

  // @@protoc_insertion_point(class_scope:M3MekaLogParam)
 private:
  inline void set_has_debug();
  inline void clear_has_debug();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double debug_;
  friend void  protobuf_AddDesc_log_2eproto();
  friend void protobuf_AssignDesc_log_2eproto();
  friend void protobuf_ShutdownFile_log_2eproto();

  void InitAsDefaultInstance();
  static M3MekaLogParam* default_instance_;
};
// -------------------------------------------------------------------

class M3MekaLogCommand : public ::google::protobuf::Message {
 public:
  M3MekaLogCommand();
  virtual ~M3MekaLogCommand();

  M3MekaLogCommand(const M3MekaLogCommand& from);

  inline M3MekaLogCommand& operator=(const M3MekaLogCommand& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const M3MekaLogCommand& default_instance();

  void Swap(M3MekaLogCommand* other);

  // implements Message ----------------------------------------------

  M3MekaLogCommand* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const M3MekaLogCommand& from);
  void MergeFrom(const M3MekaLogCommand& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double enable = 1;
  inline bool has_enable() const;
  inline void clear_enable();
  static const int kEnableFieldNumber = 1;
  inline double enable() const;
  inline void set_enable(double value);

  // @@protoc_insertion_point(class_scope:M3MekaLogCommand)
 private:
  inline void set_has_enable();
  inline void clear_has_enable();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double enable_;
  friend void  protobuf_AddDesc_log_2eproto();
  friend void protobuf_AssignDesc_log_2eproto();
  friend void protobuf_ShutdownFile_log_2eproto();

  void InitAsDefaultInstance();
  static M3MekaLogCommand* default_instance_;
};
// ===================================================================


// ===================================================================

// M3MekaLogStatus

// optional .M3BaseStatus base = 1;
inline bool M3MekaLogStatus::has_base() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void M3MekaLogStatus::set_has_base() {
  _has_bits_[0] |= 0x00000001u;
}
inline void M3MekaLogStatus::clear_has_base() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void M3MekaLogStatus::clear_base() {
  if (base_ != NULL) base_->::M3BaseStatus::Clear();
  clear_has_base();
}
inline const ::M3BaseStatus& M3MekaLogStatus::base() const {
  // @@protoc_insertion_point(field_get:M3MekaLogStatus.base)
  return base_ != NULL ? *base_ : *default_instance_->base_;
}
inline ::M3BaseStatus* M3MekaLogStatus::mutable_base() {
  set_has_base();
  if (base_ == NULL) base_ = new ::M3BaseStatus;
  // @@protoc_insertion_point(field_mutable:M3MekaLogStatus.base)
  return base_;
}
inline ::M3BaseStatus* M3MekaLogStatus::release_base() {
  clear_has_base();
  ::M3BaseStatus* temp = base_;
  base_ = NULL;
  return temp;
}
inline void M3MekaLogStatus::set_allocated_base(::M3BaseStatus* base) {
  delete base_;
  base_ = base;
  if (base) {
    set_has_base();
  } else {
    clear_has_base();
  }
  // @@protoc_insertion_point(field_set_allocated:M3MekaLogStatus.base)
}

// optional string path = 2;
inline bool M3MekaLogStatus::has_path() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void M3MekaLogStatus::set_has_path() {
  _has_bits_[0] |= 0x00000002u;
}
inline void M3MekaLogStatus::clear_has_path() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void M3MekaLogStatus::clear_path() {
  if (path_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_->clear();
  }
  clear_has_path();
}
inline const ::std::string& M3MekaLogStatus::path() const {
  // @@protoc_insertion_point(field_get:M3MekaLogStatus.path)
  return *path_;
}
inline void M3MekaLogStatus::set_path(const ::std::string& value) {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  path_->assign(value);
  // @@protoc_insertion_point(field_set:M3MekaLogStatus.path)
}
inline void M3MekaLogStatus::set_path(const char* value) {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  path_->assign(value);
  // @@protoc_insertion_point(field_set_char:M3MekaLogStatus.path)
}
inline void M3MekaLogStatus::set_path(const char* value, size_t size) {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  path_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:M3MekaLogStatus.path)
}
inline ::std::string* M3MekaLogStatus::mutable_path() {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:M3MekaLogStatus.path)
  return path_;
}
inline ::std::string* M3MekaLogStatus::release_path() {
  clear_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = path_;
    path_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void M3MekaLogStatus::set_allocated_path(::std::string* path) {
  if (path_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete path_;
  }
  if (path) {
    set_has_path();
    path_ = path;
  } else {
    clear_has_path();
    path_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:M3MekaLogStatus.path)
}

// optional string log_name = 3;
inline bool M3MekaLogStatus::has_log_name() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void M3MekaLogStatus::set_has_log_name() {
  _has_bits_[0] |= 0x00000004u;
}
inline void M3MekaLogStatus::clear_has_log_name() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void M3MekaLogStatus::clear_log_name() {
  if (log_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    log_name_->clear();
  }
  clear_has_log_name();
}
inline const ::std::string& M3MekaLogStatus::log_name() const {
  // @@protoc_insertion_point(field_get:M3MekaLogStatus.log_name)
  return *log_name_;
}
inline void M3MekaLogStatus::set_log_name(const ::std::string& value) {
  set_has_log_name();
  if (log_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    log_name_ = new ::std::string;
  }
  log_name_->assign(value);
  // @@protoc_insertion_point(field_set:M3MekaLogStatus.log_name)
}
inline void M3MekaLogStatus::set_log_name(const char* value) {
  set_has_log_name();
  if (log_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    log_name_ = new ::std::string;
  }
  log_name_->assign(value);
  // @@protoc_insertion_point(field_set_char:M3MekaLogStatus.log_name)
}
inline void M3MekaLogStatus::set_log_name(const char* value, size_t size) {
  set_has_log_name();
  if (log_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    log_name_ = new ::std::string;
  }
  log_name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:M3MekaLogStatus.log_name)
}
inline ::std::string* M3MekaLogStatus::mutable_log_name() {
  set_has_log_name();
  if (log_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    log_name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:M3MekaLogStatus.log_name)
  return log_name_;
}
inline ::std::string* M3MekaLogStatus::release_log_name() {
  clear_has_log_name();
  if (log_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = log_name_;
    log_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void M3MekaLogStatus::set_allocated_log_name(::std::string* log_name) {
  if (log_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete log_name_;
  }
  if (log_name) {
    set_has_log_name();
    log_name_ = log_name;
  } else {
    clear_has_log_name();
    log_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:M3MekaLogStatus.log_name)
}

// -------------------------------------------------------------------

// M3MekaLogParam

// optional double debug = 1;
inline bool M3MekaLogParam::has_debug() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void M3MekaLogParam::set_has_debug() {
  _has_bits_[0] |= 0x00000001u;
}
inline void M3MekaLogParam::clear_has_debug() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void M3MekaLogParam::clear_debug() {
  debug_ = 0;
  clear_has_debug();
}
inline double M3MekaLogParam::debug() const {
  // @@protoc_insertion_point(field_get:M3MekaLogParam.debug)
  return debug_;
}
inline void M3MekaLogParam::set_debug(double value) {
  set_has_debug();
  debug_ = value;
  // @@protoc_insertion_point(field_set:M3MekaLogParam.debug)
}

// -------------------------------------------------------------------

// M3MekaLogCommand

// optional double enable = 1;
inline bool M3MekaLogCommand::has_enable() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void M3MekaLogCommand::set_has_enable() {
  _has_bits_[0] |= 0x00000001u;
}
inline void M3MekaLogCommand::clear_has_enable() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void M3MekaLogCommand::clear_enable() {
  enable_ = 0;
  clear_has_enable();
}
inline double M3MekaLogCommand::enable() const {
  // @@protoc_insertion_point(field_get:M3MekaLogCommand.enable)
  return enable_;
}
inline void M3MekaLogCommand::set_enable(double value) {
  set_has_enable();
  enable_ = value;
  // @@protoc_insertion_point(field_set:M3MekaLogCommand.enable)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_log_2eproto__INCLUDED
