language: cpp

compiler:
  - gcc
  - clang

before_install:
  - export CI_SOURCE_PATH=$(pwd)
  - wget http://yaml-cpp.googlecode.com/files/yaml-cpp-0.3.0.tar.gz
  - tar -xf yaml-cpp-0.3.0.tar.gz
  - cd yaml-cpp
  - mkdir build;cd build;
  - cmake .. -DBUILD_SHARED_LIBS=1
  - make -j$(nproc)
  - sudo make install
  
install:
  - cd $CI_SOURCE_PATH
  - mkdir build
  - cd build
  - cmake .. 
  
script:
  - make && sudo make install
