#!/bin/bash
export LD_LIBRARY_PATH=/usr/local/share:/usr/local/lib:$LD_LIBRARY_PATH
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
export PYTHONPATH=/usr/local/lib/python2.7/dist-packages/:/usr/local/lib/python2.7/dist-packages/m3:~/mekabot/m3ens-utils/python:$PYTHONPATH

